name: smart_school_management_platform

description: A Flutter project for managing school operations.

version: 1.0.0+

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.0
  http: ^0.13.4
  shared_preferences: ^2.0.6
  firebase_core: ^1.10.0
  firebase_auth: ^3.3.10
  cloud_firestore: ^3.1.5
  flutter_localizations:
    sdk: flutter

flutter:
  uses-material-design: true
